import Head from 'next/head'
import NavBar from '../components/templates/NavBar'

import Header from '../components/organisms/header'
import Footer from '../components/molecules/footer'

export default function Home() {


  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <NavBar />
      <main >
        <Header/>
        <h1 className="text-3xl font-bold underline">
          Contenido principal
        </h1>

      </main>

      <Footer/>
    </div>
  )
}
